#pragma once

// On-disk layout of the Library index (`CLX1`), plus the pure validation and
// offset arithmetic around it.
//
// Deliberately free of HalStorage and Arduino so the whole layout is
// host-testable (test/library_format). File I/O lives in LibraryIndexFile.
//
// Layout, in order, every section starting on a 512-byte boundary:
//
//   header        64 bytes of struct, padded to 512
//   folders       F variable-length records; the id of a folder IS its ordinal
//   records       N x exactly 128 bytes, in folded sort-title order
//   lists         ClixListDesc[listCount], then u16 list entries and list labels
//   names         path hash, filename, display author, title, source author,
//                 author sort (file-as), series, series index and tags blobs
//
// Lists 0..2 are always Recent, Title and Author. Title is the record order
// itself and stores no entries. Later lists are generated by the builder
// (Series, Tags, Folders, as the library settings ask) or written by external
// tools: a Books list names any subset of records, a Groups list names other
// lists, each of which opens as its own row, and a Mixed list names both.
//
// The fixed 128-byte record stride is the load-bearing choice: record k lives at
// recordStart + 128k, so paging is O(1) in every sort order with no offset
// table; 32 records fill a 4096-byte buffer exactly, so a streaming scan never
// straddles a record; and since recordStart is 512-aligned and 128 divides 512,
// every chunk read is aligned by construction rather than by remembering to.

#include <cstddef>
#include <cstdint>

namespace library {

inline constexpr char CLIX_MAGIC[4] = {'C', 'L', 'X', '1'};
// Bumping this is the whole migration: an index from an older version fails
// validation and is rebuilt. No previous development format is accepted.
inline constexpr uint8_t CLIX_FORMAT_VERSION = 3;
// Same folders, records and name blob as the current version, so a rebuild
// still reads its books to keep their arrival history.
inline constexpr uint8_t CLIX_PREVIOUS_FORMAT_VERSION = 2;

// Bump when the fold or a permutation's sort key changes.
// Forces fold and ranks to be rebuilt while firstSeen values are preserved, so
// arrival history survives.
// v5: records fold the book's title sort (file-as) when it has one, the author
// order uses the author's file-as, and the name blob gains an author-sort field.
// v6: the name blob gains series, series index and tags fields.
inline constexpr uint8_t CLIX_FOLD_VERSION = 6;

inline constexpr uint32_t CLIX_ALIGN = 512;
inline constexpr size_t CLIX_FOLD_BYTES = 96;
inline constexpr size_t CLIX_AUTHOR_KEY_BYTES = 12;

// A 2000-book card already produces a 429 KiB index. This hard bound keeps every
// record count and permutation ordinal representable by uint16_t.
inline constexpr uint16_t CLIX_MAX_RECORDS = 4096;
// Keeps list ids, like record ordinals, in a u16 with room for the 0xFFFF
// "none" marker.
inline constexpr uint16_t CLIX_MAX_LISTS = 4096;

inline constexpr uint16_t CLIX_RECENT_LIST = 0;
inline constexpr uint16_t CLIX_TITLE_LIST = 1;
inline constexpr uint16_t CLIX_AUTHOR_LIST = 2;
inline constexpr uint16_t CLIX_BUILTIN_LISTS = 3;

// A Mixed list entry with this bit set names a list (the low bits are its id);
// without it, a record ordinal. Both stay below it by CLIX_MAX_RECORDS/LISTS.
inline constexpr uint16_t CLIX_ENTRY_LIST_BIT = 0x8000;

// Which lists a build produced (header.listOptions), from the library
// settings. Recent, Title and Author are always written; their bit decides only
// whether they are shown as top-level lists.
enum ClixListOption : uint8_t {
  CLIX_OPTION_RECENT = 1 << 0,
  CLIX_OPTION_TITLE = 1 << 1,
  CLIX_OPTION_AUTHOR = 1 << 2,
  CLIX_OPTION_SERIES = 1 << 3,
  CLIX_OPTION_TAGS = 1 << 4,
  CLIX_OPTION_FOLDERS = 1 << 5,
  CLIX_OPTION_CUSTOM = 1 << 6,  // the lists described by the custom lists file
};
inline constexpr uint8_t CLIX_OPTIONS_DEFAULT = CLIX_OPTION_RECENT | CLIX_OPTION_TITLE | CLIX_OPTION_AUTHOR;
inline constexpr uint8_t CLIX_OPTIONS_ALL = 0x7F;
inline constexpr uint8_t CLIX_OPTIONS_GENERATED =
    CLIX_OPTION_SERIES | CLIX_OPTION_TAGS | CLIX_OPTION_FOLDERS | CLIX_OPTION_CUSTOM;

// Complete-path fingerprint stored in front of every record's name blob.
// Shared by the builder's reconciliation and the browser's recent-book lookup,
// which must agree byte-for-byte on the hash of the same path.
inline uint64_t clixPathHash(const char* data, const size_t len) {
  uint64_t hash = 14695981039346656037ULL;  // FNV-1a 64
  for (size_t i = 0; i < len; i++) {
    hash ^= static_cast<unsigned char>(data[i]);
    hash *= 1099511628211ULL;
  }
  return hash;
}

enum ClixFlags : uint8_t {
  CLIX_FLAG_RANKS_DEGRADED = 1 << 0,
  CLIX_FLAG_DEDUP_DEGRADED = 1 << 1,
  // External lists from the previous index could not be carried into this one.
  CLIX_FLAG_LISTS_DROPPED = 1 << 2,
  // A generated list the settings asked for was left out (memory or limits).
  CLIX_FLAG_LISTS_INCOMPLETE = 1 << 3,
};

enum ClixListKind : uint8_t {
  CLIX_LIST_IDENTITY = 0,  // every record, in record (title) order; no entries
  CLIX_LIST_BOOKS = 1,     // entries are record ordinals
  CLIX_LIST_GROUPS = 2,    // entries are ids of later lists
  CLIX_LIST_MIXED = 3,     // entries are either; see CLIX_ENTRY_LIST_BIT
};

// Built-in and generated top-level lists carry no label and are named by the
// firmware. Generated lists (every role past AUTHOR) are rebuilt from the
// books on every build; only external lists are carried over.
enum ClixListRole : uint8_t {
  CLIX_ROLE_EXTERNAL = 0,
  CLIX_ROLE_RECENT = 1,
  CLIX_ROLE_TITLE = 2,
  CLIX_ROLE_AUTHOR = 3,
  CLIX_ROLE_SERIES = 4,     // Groups of per-series lists
  CLIX_ROLE_TAGS = 5,       // Groups of per-tag lists
  CLIX_ROLE_FOLDERS = 6,    // Mixed: the card's root folder
  CLIX_ROLE_GENERATED = 7,  // a child of a generated list; labelled
  CLIX_ROLE_CUSTOM = 8,     // from the custom lists file: Groups of per-tag lists, or one tag's Books; labelled
};

// The icon shown beside a list's row. DEFAULT, and any value this firmware does
// not know, falls back to one chosen from the list's role, then its kind.
enum ClixListIcon : uint8_t {
  CLIX_ICON_DEFAULT = 0,
  CLIX_ICON_LIST = 1,
  CLIX_ICON_FOLDER = 2,
  CLIX_ICON_FOLDER_TREE = 3,
  CLIX_ICON_BOOK = 4,
  CLIX_ICON_BOOKS = 5,
  CLIX_ICON_RECENT = 6,
  CLIX_ICON_TITLE = 7,
  CLIX_ICON_AUTHOR = 8,
  CLIX_ICON_SERIES = 9,
  CLIX_ICON_SERIES_ENTRY = 10,
  CLIX_ICON_TAGS = 11,
  CLIX_ICON_TAG = 12,
  CLIX_ICON_BOOKMARK = 13,
  CLIX_ICON_STAR = 14,
  CLIX_ICON_HEART = 15,
};

enum ClixListFlags : uint8_t {
  CLIX_LIST_TOP_LEVEL = 1 << 0,
};

enum ClixMetadataStatus : uint8_t {
  CLIX_METADATA_NOT_ATTEMPTED = 0,
  CLIX_METADATA_EXTRACTED = 1,
  CLIX_METADATA_FAILED = 2,
};

#pragma pack(push, 1)

struct ClixHeader {
  char magic[4];
  uint8_t formatVersion;
  uint8_t foldVersion;
  uint8_t flags;
  uint8_t metadataEnabled;
  uint16_t bookCount;
  uint16_t folderCount;
  uint16_t nextFirstSeen;
  uint16_t padding1;
  uint32_t folderStart;
  uint32_t folderLen;
  uint32_t recordStart;
  uint32_t listStart;
  uint32_t nameStart;
  uint32_t nameLen;
  // Expected total file size. Comparing it with the real size is a free
  // truncation guard: a build interrupted by a power cut cannot pass.
  uint32_t selfSize;
  uint32_t listLen;
  uint16_t listCount;
  uint8_t listOptions;  // ClixListOption bits this build was asked for
  // Fingerprint of the custom lists file the build read (0: none, or the
  // Custom option off), so an edited file triggers a rebuild.
  uint32_t customListsHash;
  uint8_t reserved[9];
};
static_assert(sizeof(ClixHeader) == 64, "ClixHeader must be exactly 64 bytes");

struct ClixRecord {
  uint32_t nameOff;   // from nameStart, into the per-record name blob
  uint32_t fileSize;  // captured while the dirent was open; part of the identity
  uint16_t firstSeen;
  uint16_t folderId;
  uint8_t nameLen;
  uint8_t foldLen;
  uint8_t authorKeyLen;
  uint8_t metadataStatus;
  // Folded title sort when the book has one, else the folded shown title. The
  // records are in this order; search also matches the shown title's fold.
  char fold[CLIX_FOLD_BYTES];
  char authorKey[CLIX_AUTHOR_KEY_BYTES];
  uint32_t modificationTime;
};
static_assert(sizeof(ClixRecord) == 128, "ClixRecord must be exactly 128 bytes");
static_assert(CLIX_ALIGN % sizeof(ClixRecord) == 0, "records must tile a 512-byte sector");

struct ClixFolderHeader {
  uint8_t pathLen;  // 1..255; the path bytes follow, with no trailing '/'
};
static_assert(sizeof(ClixFolderHeader) == 1, "ClixFolderHeader must be 1 byte");

// One list. Offsets are from listStart, so the table, the entries and the
// labels can sit anywhere in the list section.
struct ClixListDesc {
  uint8_t kind;   // ClixListKind
  uint8_t role;   // ClixListRole; built-in lists carry no label and use tr()
  uint8_t flags;  // ClixListFlags
  uint8_t labelLen;
  uint16_t entryCount;  // rows; bookCount for an identity list
  uint8_t icon;         // ClixListIcon
  uint8_t reserved;
  uint32_t entriesOff;  // u16[entryCount]; unused by an identity list
  uint32_t labelOff;    // UTF-8, labelLen bytes
};
static_assert(sizeof(ClixListDesc) == 16, "ClixListDesc must be exactly 16 bytes");

#pragma pack(pop)

inline uint32_t alignUp(const uint32_t value) { return (value + CLIX_ALIGN - 1) / CLIX_ALIGN * CLIX_ALIGN; }

// Fill in every offset and the expected file size from the section lengths
// alone, so the writer and the reader can never disagree about where a section
// starts.
inline void layoutSections(ClixHeader& h, const uint32_t folderBytes, const uint32_t listBytes,
                           const uint32_t nameBytes) {
  h.folderStart = CLIX_ALIGN;
  h.folderLen = folderBytes;
  h.recordStart = alignUp(h.folderStart + folderBytes);
  h.listStart = alignUp(h.recordStart + static_cast<uint32_t>(h.bookCount) * sizeof(ClixRecord));
  h.listLen = listBytes;
  h.nameStart = alignUp(h.listStart + listBytes);
  h.nameLen = nameBytes;
  h.selfSize = h.nameStart + nameBytes;
}

inline uint32_t recordOffset(const ClixHeader& h, const uint16_t ordinal) {
  return h.recordStart + static_cast<uint32_t>(ordinal) * sizeof(ClixRecord);
}

// The three built-in lists for an index holding `listCount` lists in all.
// Their entries (Recent, then Author) follow the whole descriptor table. Each
// is top-level when its ClixListOption bit is set.
inline uint32_t builtinListEntryBytes(const uint16_t books) { return 2u * books * sizeof(uint16_t); }
inline void builtinListDescs(ClixListDesc* out, const uint16_t books, const uint16_t listCount,
                             const uint8_t options = CLIX_OPTIONS_DEFAULT) {
  const uint32_t table = static_cast<uint32_t>(listCount) * sizeof(ClixListDesc);
  const auto top = [options](const uint8_t option) {
    return static_cast<uint8_t>((options & option) != 0 ? CLIX_LIST_TOP_LEVEL : 0);
  };
  out[CLIX_RECENT_LIST] = {
      CLIX_LIST_BOOKS, CLIX_ROLE_RECENT, top(CLIX_OPTION_RECENT), 0, books, CLIX_ICON_RECENT, 0, table, 0};
  out[CLIX_TITLE_LIST] = {
      CLIX_LIST_IDENTITY, CLIX_ROLE_TITLE, top(CLIX_OPTION_TITLE), 0, books, CLIX_ICON_TITLE, 0, 0, 0};
  out[CLIX_AUTHOR_LIST] = {
      CLIX_LIST_BOOKS, CLIX_ROLE_AUTHOR, top(CLIX_OPTION_AUTHOR), 0, books, CLIX_ICON_AUTHOR, 0, table + books * 2u, 0};
}

// The icon to show for a list: its own when this firmware knows it, else one
// for its role, else one for its kind.
inline ClixListIcon listIcon(const ClixListDesc& list) {
  if (list.icon != CLIX_ICON_DEFAULT && list.icon <= CLIX_ICON_HEART) return static_cast<ClixListIcon>(list.icon);
  switch (list.role) {
    case CLIX_ROLE_RECENT:
      return CLIX_ICON_RECENT;
    case CLIX_ROLE_TITLE:
      return CLIX_ICON_TITLE;
    case CLIX_ROLE_AUTHOR:
      return CLIX_ICON_AUTHOR;
    case CLIX_ROLE_SERIES:
      return CLIX_ICON_SERIES;
    case CLIX_ROLE_TAGS:
    case CLIX_ROLE_CUSTOM:
      return CLIX_ICON_TAGS;
    case CLIX_ROLE_FOLDERS:
      return CLIX_ICON_FOLDER_TREE;
    default:
      break;
  }
  switch (list.kind) {
    case CLIX_LIST_GROUPS:
      return CLIX_ICON_FOLDER;
    case CLIX_LIST_MIXED:
      return CLIX_ICON_FOLDER;
    default:
      return CLIX_ICON_LIST;
  }
}

// Why a loaded index was rejected. Reported rather than swallowed so a rebuild
// loop caused by a format bug shows up in the log instead of looking like a slow
// first boot.
enum class ClixValidity : uint8_t {
  Ok,
  BadMagic,
  UnknownFormatVersion,
  StaleFoldVersion,
  SizeMismatch,  // truncated, or a build interrupted before the final rename
  CountOutOfRange,
  SectionsInconsistent,
  ListsInconsistent,  // a built-in list descriptor is missing or malformed
};

// Validate a header against the real file size. Cheap enough to run on the one
// sector already read, and strict enough that nothing downstream has to
// re-check bounds. `acceptPreviousFormat` admits a CLIX_PREVIOUS_FORMAT_VERSION
// file, whose records and names a rebuild can still read; it has no lists.
inline ClixValidity validateHeaderStructure(const ClixHeader& h, const uint64_t actualFileSize,
                                            const bool acceptPreviousFormat = false) {
  for (size_t i = 0; i < sizeof(CLIX_MAGIC); i++) {
    if (h.magic[i] != CLIX_MAGIC[i]) return ClixValidity::BadMagic;
  }
  const bool previousFormat = acceptPreviousFormat && h.formatVersion == CLIX_PREVIOUS_FORMAT_VERSION;
  if (h.formatVersion != CLIX_FORMAT_VERSION && !previousFormat) return ClixValidity::UnknownFormatVersion;
  if (h.bookCount > CLIX_MAX_RECORDS) return ClixValidity::CountOutOfRange;
  if (h.metadataEnabled > 1) return ClixValidity::SectionsInconsistent;
  if (actualFileSize != h.selfSize) return ClixValidity::SizeMismatch;

  // These lengths are attacker-controlled bytes. Capped against the real file
  // size they cannot wrap the 32-bit section sums below, so the layout
  // comparison stays sound instead of re-deriving the same wrapped values.
  if (h.folderLen > actualFileSize || h.nameLen > actualFileSize) return ClixValidity::SectionsInconsistent;

  // The previous format's author and arrival orders occupy the list section's
  // place, and its header has no list fields.
  const uint32_t listBytes = previousFormat ? builtinListEntryBytes(h.bookCount) : h.listLen;
  if (!previousFormat) {
    if (h.listLen > actualFileSize) return ClixValidity::SectionsInconsistent;
    if (h.listCount < CLIX_BUILTIN_LISTS || h.listCount > CLIX_MAX_LISTS ||
        static_cast<uint32_t>(h.listCount) * sizeof(ClixListDesc) > h.listLen) {
      return ClixValidity::ListsInconsistent;
    }
  }

  ClixHeader expected = h;
  layoutSections(expected, h.folderLen, listBytes, h.nameLen);
  if (expected.folderStart != h.folderStart || expected.recordStart != h.recordStart ||
      expected.listStart != h.listStart || expected.nameStart != h.nameStart || expected.selfSize != h.selfSize) {
    return ClixValidity::SectionsInconsistent;
  }
  return ClixValidity::Ok;
}

// Validate list `id`'s descriptor against a header that passed
// validateHeaderStructure. Entry VALUES are checked as they are read.
inline bool validateListDesc(const ClixHeader& h, const uint16_t id, const ClixListDesc& d) {
  if (id >= h.listCount || d.kind > CLIX_LIST_MIXED || d.role > CLIX_ROLE_CUSTOM) return false;
  if (d.labelLen > 0 && (d.labelOff > h.listLen || d.labelLen > h.listLen - d.labelOff)) return false;
  if (d.kind == CLIX_LIST_IDENTITY) {
    if (d.entryCount != h.bookCount) return false;
  } else if (d.entriesOff > h.listLen || static_cast<uint32_t>(d.entryCount) * 2u > h.listLen - d.entriesOff) {
    return false;
  }
  if (id >= CLIX_BUILTIN_LISTS) return d.role == CLIX_ROLE_EXTERNAL || d.role >= CLIX_ROLE_SERIES;
  // Built-in lists are fixed: Recent and Author name every book, and Title is
  // the record order.
  if (d.role != id + 1) return false;
  if (id == CLIX_TITLE_LIST) return d.kind == CLIX_LIST_IDENTITY;
  return d.kind == CLIX_LIST_BOOKS && d.entryCount == h.bookCount;
}

inline ClixValidity validateHeader(const ClixHeader& h, const uint64_t actualFileSize) {
  const ClixValidity structure = validateHeaderStructure(h, actualFileSize);
  if (structure != ClixValidity::Ok) return structure;
  return h.foldVersion == CLIX_FOLD_VERSION ? ClixValidity::Ok : ClixValidity::StaleFoldVersion;
}

const char* clixValidityName(ClixValidity v);

}  // namespace library
